travis:
  secure:
    BINSTAR_TOKEN: hHU7R9y+l6zvfU5VHMoBe+2zeAZz7XXfHWLFdsQlKkBT61qGt0LzVWi/a4JKcWnMGqSz1SC+rKPi2ZXhTTKEpoByq0tc9h9rgMkTBMnQWwY5Rm2EjX5geRpPAftXnaMA+9NkubR559VCpETIE5Dm2+anVeVbOcP175aFqbpGJG0NBl930KQ6ioH8r0L+09Jy3ENoYiKlgZylcWmRSyjb+pREbUaU9JbrAGpg416gxB9hFdW03wHbLpMjzR4ddH8BqLfSV41AnxJweTtmqfp+7cOO+CWl+6abrbkB0WEpN40xLThTnfSWz2XkCt7cvjsoP4nLY0Vabtxs5c6AalhuRnmHJxIvfYdY5tn0CnfPQEm8AEfEC1kEs+IN1Vsa6dF9lvL34wj/SYlGLr2vJ9RQ7Gq+pQZSji2m+BtpKLp5qsUvatNB35nqBVLX39CofZoLYlF+t17wEoOrn6hrN8IlyCXPjrHw/MunL9uhjZI4TNnf9CUfea/QBR61iPCkU2Uy5/Y3xySz+9a2c7Vmv1ImgjipGeeJoJEprGGqixP8MQ3wwLT1LZd2VnRwYkvpnUtYao76/HkInss+WEhcJAZhvG6y71XpBTXgGIYkTi28s+lhtMTr+giupB2Ub5oCCDN+8stqcUGbctC6DM063ZwBOyPdD49c6YmprwrdvchRTEM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
