travis:
  secure:
    BINSTAR_TOKEN: ovyeIXEiFqFGx5H9x7whMyKluAnKWTYJvguDjFgEtFE3jSk4IxWJ0IcTqPEn3Ru0v1qOKbnYKvogp7H5JlsLqemWi30IKPsjY1viKXpGc706g/tzO0qMFPVqUE9ht+DwYkNleriHDlJt3HhUlMrYg19a2S5hRQruGCI0ZPQ6RyuZEtN8dwh+8HzWhehi8OmrCgQ2hMxHA1iRp+QiJhcjS/uf+impJ+3m+fWnpbwZpjobdYXwgK6Y4GX6PFmnEzCbfmiOgDh59gY1akVASoYKzmbIL69ui/qwox5Vh0M9yzAC7QMb5belq5IdeQCXGO515sXPOxxolVAhggmzHVWYYzt7//RIYMe8jgaBtjd0nQDNHC1SrSWOJS+EWdj89cf8rncEniDfHIZzPr9MGeGLvj3pRu+jRARSGRJNV0K+np0Z+Pzk6kp6wYq8j1PT3Kiu/6QQxrAfCB0abC1G52PBJMPPuhm3Sk9O7Au6tGNi2Urhn2EI/ZZlP+PTuIgLeEvpJaf/avf/Bmytu6N3RIo6BvkvX4gBvT6v2Vqg8mhfxGK3VWJnPceGlTo0LAAMh7OCn6Xoj3mJaKlleJtBsAHvjXsLdNBxDqb3bt1GOI6uD5CjoIEUq0rdTkxbkC2ozwqNmMYg2m9Rjs04yU93bVs47BwvDUdv4U2wylkYF4QOOic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
