travis:
  secure:
    BINSTAR_TOKEN: jrHsIgowGS02LMY5iP7bOgugZveh1UAsp6pAZArMWMFqGK5dYYuLZ3S705ee0XJZjPMVEpgmZX5e6UcObDyBRhFNLFi+CaJXpvmptZVo53qV6aSPC2vogHb72i+f9i/VGi9HI9GO8ItF3SO6LQ/UEtnKxvekC3pgSXIqoZeo2NMRWu5HZIk4mwEghtGRTDShpfnhqqlxQazXF0e/kR7T6EvUZeGA9WjGMTh4DnJAAC6Uq2xV4GOjgvY9NFdHcXdn6TwWGVnXDkGzTHNSBV9XP185kvXBpMLFpHx7DpWWO/O9Ra/2aKEXpDjTP32QcXFcjGXAOcQ4Eizxma07Wl5DUtIArcjGqbVrG0GvmyHNbwgA+viIEzN986lQTg/Ab1dEu7RjW5rsWGj/ER2fjQJ/OivyPoeSaVUapwy5cPqFLAFWDh6ptOoi62iWkaIjq6BaD1YMD5H5YziTlhuy5JuMVYatH9fUhKLsqRyNr05EnH6xHWe4qm8QMyNSS1iHcc8eSMFZp60U7vUkVnu5Fhi5MbjUmnVnpIhmuZdxpsJKPk0V8xz8xZn3LoPUWx3Z0KaYSTSG6gXowcyWde6lsCJx8Kie8A1D8ExK+b72+ugc+BIgaaCjQcNLWHEDsvMMkbHQtaM2hxhwenR6mTOAR89Pl11Jb+xO6R23gNpjwJWQ2n0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
